// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/book.dart';
import 'models/document.dart';
import 'models/note.dart';
import 'models/search_history.dart';
import 'models/subject.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6994002034456230376),
    name: 'Book',
    lastPropertyId: const obx_int.IdUid(20, 3449543017502837907),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6358533305905572571),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6334888184427432029),
        name: 'bookId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(1, 1738416300974585639),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8401359158674599255),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 9002311712711712314),
        name: 'author',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5597918087425287131),
        name: 'isbn',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3726609697902381061),
        name: 'subject',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(2, 5626503123904025882),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4819681371730635566),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 3117104974410190460),
        name: 'publisher',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4676519821093452720),
        name: 'publicationDate',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4426460074096809958),
        name: 'coverImagePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 294067890071921152),
        name: 'barcodePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 6868773947914448835),
        name: 'tags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 8098346238688942963),
        name: 'addedAt',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(3, 4801596553768706954),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 126331811735849783),
        name: 'lastAccessedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 7878812663188366998),
        name: 'accessCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 6181021814830812780),
        name: 'totalPages',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 4463807516500383831),
        name: 'currentPage',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 2923232890553988791),
        name: 'readingStatus',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(19, 519445137076295214),
        name: 'isFavorite',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(20, 3449543017502837907),
        name: 'isArchived',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 6830643742148006931),
    name: 'Document',
    lastPropertyId: const obx_int.IdUid(18, 4127495236764716573),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1327159035481194819),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7486049056631788249),
        name: 'documentId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 7913358069886998568),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4974086187552735432),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 309888574481448892),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 277921904492758131),
        name: 'subject',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 7676416924442476251),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8150350205707384519),
        name: 'filePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2073329602236626695),
        name: 'fileName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 547112240404991731),
        name: 'tags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 5719943185038257514),
        name: 'extractedText',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5176893058802835675),
        name: 'createdAt',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(6, 4628381356371867419),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 195305575335923101),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 541841056371637173),
        name: 'lastAccessedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 2199752316648415011),
        name: 'accessCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 7067986916683978631),
        name: 'documentType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 3631227242868007345),
        name: 'thumbnailPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 7281203469691188024),
        name: 'fileSize',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(17, 5440442158710142347),
        name: 'isFavorite',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(18, 4127495236764716573),
        name: 'isArchived',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 7853324664982390250),
    name: 'Note',
    lastPropertyId: const obx_int.IdUid(16, 2470213486495683442),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3838415241898978035),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8503320551079649442),
        name: 'noteId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(7, 95828124811368577),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 739393343135047027),
        name: 'title',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5085329292598530481),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 3915355437660305681),
        name: 'subject',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(8, 2830797378911868160),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7898532595941311014),
        name: 'tags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 348030190478348154),
        name: 'createdAt',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(9, 3787578784003422809),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8065811803165159310),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4546892666695736195),
        name: 'lastAccessedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3009961911558613341),
        name: 'accessCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2590646729946836434),
        name: 'noteType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 9173889900661455113),
        name: 'handwritingImagePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 476838196061503057),
        name: 'thumbnailPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 2017547981530483676),
        name: 'isFavorite',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 4805171122836278837),
        name: 'isArchived',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(16, 2470213486495683442),
        name: 'digitizedInkData',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5627288773554431285),
    name: 'SearchHistory',
    lastPropertyId: const obx_int.IdUid(5, 1142290112893444437),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5958371714867046544),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6393109170877286239),
        name: 'query',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(10, 822224689659938281),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2461440115101968081),
        name: 'searchedAt',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(11, 5691393056049979796),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2182654155113183545),
        name: 'resultCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1142290112893444437),
        name: 'resultType',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(5, 6431252661591171238),
    name: 'Subject',
    lastPropertyId: const obx_int.IdUid(11, 1042536813054092931),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7818695375213999502),
        name: 'id',
        type: 6,
        flags: 129,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4666278735561693194),
        name: 'subjectId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(12, 5222565635319001646),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1970420996589471831),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8555255287254379452),
        name: 'description',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8492901150699696019),
        name: 'iconPath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2702272086403602922),
        name: 'color',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 337000964043306848),
        name: 'createdAt',
        type: 10,
        flags: 8,
        indexId: const obx_int.IdUid(13, 8256140465995371502),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 8277269141035751357),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6722446360112567998),
        name: 'documentCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 4674267128060601087),
        name: 'noteCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1042536813054092931),
        name: 'bookCount',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(5, 6431252661591171238),
    lastIndexId: const obx_int.IdUid(13, 8256140465995371502),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    Book: obx_int.EntityDefinition<Book>(
      model: _entities[0],
      toOneRelations: (Book object) => [],
      toManyRelations: (Book object) => {},
      getId: (Book object) => object.id,
      setId: (Book object, int id) {
        object.id = id;
      },
      objectToFB: (Book object, fb.Builder fbb) {
        final bookIdOffset = fbb.writeString(object.bookId);
        final titleOffset = fbb.writeString(object.title);
        final authorOffset = fbb.writeString(object.author);
        final isbnOffset = fbb.writeString(object.isbn);
        final subjectOffset = fbb.writeString(object.subject);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final publisherOffset = object.publisher == null
            ? null
            : fbb.writeString(object.publisher!);
        final publicationDateOffset = object.publicationDate == null
            ? null
            : fbb.writeString(object.publicationDate!);
        final coverImagePathOffset = object.coverImagePath == null
            ? null
            : fbb.writeString(object.coverImagePath!);
        final barcodePathOffset = object.barcodePath == null
            ? null
            : fbb.writeString(object.barcodePath!);
        final tagsOffset = fbb.writeList(
          object.tags.map(fbb.writeString).toList(growable: false),
        );
        final readingStatusOffset = fbb.writeString(object.readingStatus);
        fbb.startTable(21);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, bookIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, authorOffset);
        fbb.addOffset(4, isbnOffset);
        fbb.addOffset(5, subjectOffset);
        fbb.addOffset(6, descriptionOffset);
        fbb.addOffset(7, publisherOffset);
        fbb.addOffset(8, publicationDateOffset);
        fbb.addOffset(9, coverImagePathOffset);
        fbb.addOffset(10, barcodePathOffset);
        fbb.addOffset(11, tagsOffset);
        fbb.addInt64(12, object.addedAt.millisecondsSinceEpoch);
        fbb.addInt64(13, object.lastAccessedAt?.millisecondsSinceEpoch);
        fbb.addInt64(14, object.accessCount);
        fbb.addInt64(15, object.totalPages);
        fbb.addInt64(16, object.currentPage);
        fbb.addOffset(17, readingStatusOffset);
        fbb.addBool(18, object.isFavorite);
        fbb.addBool(19, object.isArchived);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final lastAccessedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          30,
        );
        final bookIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final authorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final isbnParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final subjectParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 16);
        final publisherParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 18);
        final publicationDateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final coverImagePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final barcodePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final tagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 26, []);
        final addedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0),
        );
        final lastAccessedAtParam = lastAccessedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastAccessedAtValue);
        final accessCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          32,
          0,
        );
        final totalPagesParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          34,
          0,
        );
        final currentPageParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          36,
          0,
        );
        final readingStatusParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 38, '');
        final isFavoriteParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          40,
          false,
        );
        final isArchivedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          42,
          false,
        );
        final object = Book(
          bookId: bookIdParam,
          title: titleParam,
          author: authorParam,
          isbn: isbnParam,
          subject: subjectParam,
          description: descriptionParam,
          publisher: publisherParam,
          publicationDate: publicationDateParam,
          coverImagePath: coverImagePathParam,
          barcodePath: barcodePathParam,
          tags: tagsParam,
          addedAt: addedAtParam,
          lastAccessedAt: lastAccessedAtParam,
          accessCount: accessCountParam,
          totalPages: totalPagesParam,
          currentPage: currentPageParam,
          readingStatus: readingStatusParam,
          isFavorite: isFavoriteParam,
          isArchived: isArchivedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    Document: obx_int.EntityDefinition<Document>(
      model: _entities[1],
      toOneRelations: (Document object) => [],
      toManyRelations: (Document object) => {},
      getId: (Document object) => object.id,
      setId: (Document object, int id) {
        object.id = id;
      },
      objectToFB: (Document object, fb.Builder fbb) {
        final documentIdOffset = fbb.writeString(object.documentId);
        final titleOffset = fbb.writeString(object.title);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final subjectOffset = fbb.writeString(object.subject);
        final filePathOffset = fbb.writeString(object.filePath);
        final fileNameOffset = fbb.writeString(object.fileName);
        final tagsOffset = fbb.writeList(
          object.tags.map(fbb.writeString).toList(growable: false),
        );
        final extractedTextOffset = object.extractedText == null
            ? null
            : fbb.writeList(
                object.extractedText!
                    .map(fbb.writeString)
                    .toList(growable: false),
              );
        final documentTypeOffset = fbb.writeString(object.documentType);
        final thumbnailPathOffset = object.thumbnailPath == null
            ? null
            : fbb.writeString(object.thumbnailPath!);
        fbb.startTable(19);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, documentIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addOffset(4, subjectOffset);
        fbb.addOffset(5, filePathOffset);
        fbb.addOffset(6, fileNameOffset);
        fbb.addOffset(7, tagsOffset);
        fbb.addOffset(8, extractedTextOffset);
        fbb.addInt64(9, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(10, object.updatedAt?.millisecondsSinceEpoch);
        fbb.addInt64(11, object.lastAccessedAt?.millisecondsSinceEpoch);
        fbb.addInt64(12, object.accessCount);
        fbb.addOffset(13, documentTypeOffset);
        fbb.addOffset(14, thumbnailPathOffset);
        fbb.addInt64(15, object.fileSize);
        fbb.addBool(16, object.isFavorite);
        fbb.addBool(17, object.isArchived);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final updatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          24,
        );
        final lastAccessedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          26,
        );
        final documentIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final subjectParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final filePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final fileNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final documentTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 30, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final tagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 18, []);
        final extractedTextParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 20);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0),
        );
        final updatedAtParam = updatedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
        final lastAccessedAtParam = lastAccessedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastAccessedAtValue);
        final accessCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          28,
          0,
        );
        final thumbnailPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 32);
        final fileSizeParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          34,
          0,
        );
        final isFavoriteParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          36,
          false,
        );
        final isArchivedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          38,
          false,
        );
        final object = Document(
          documentId: documentIdParam,
          title: titleParam,
          subject: subjectParam,
          filePath: filePathParam,
          fileName: fileNameParam,
          documentType: documentTypeParam,
          description: descriptionParam,
          tags: tagsParam,
          extractedText: extractedTextParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          lastAccessedAt: lastAccessedAtParam,
          accessCount: accessCountParam,
          thumbnailPath: thumbnailPathParam,
          fileSize: fileSizeParam,
          isFavorite: isFavoriteParam,
          isArchived: isArchivedParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    Note: obx_int.EntityDefinition<Note>(
      model: _entities[2],
      toOneRelations: (Note object) => [],
      toManyRelations: (Note object) => {},
      getId: (Note object) => object.id,
      setId: (Note object, int id) {
        object.id = id;
      },
      objectToFB: (Note object, fb.Builder fbb) {
        final noteIdOffset = fbb.writeString(object.noteId);
        final titleOffset = fbb.writeString(object.title);
        final contentOffset = fbb.writeString(object.content);
        final subjectOffset = fbb.writeString(object.subject);
        final tagsOffset = fbb.writeList(
          object.tags.map(fbb.writeString).toList(growable: false),
        );
        final noteTypeOffset = fbb.writeString(object.noteType);
        final handwritingImagePathOffset = object.handwritingImagePath == null
            ? null
            : fbb.writeString(object.handwritingImagePath!);
        final thumbnailPathOffset = object.thumbnailPath == null
            ? null
            : fbb.writeString(object.thumbnailPath!);
        final digitizedInkDataOffset = object.digitizedInkData == null
            ? null
            : fbb.writeString(object.digitizedInkData!);
        fbb.startTable(17);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, noteIdOffset);
        fbb.addOffset(2, titleOffset);
        fbb.addOffset(3, contentOffset);
        fbb.addOffset(4, subjectOffset);
        fbb.addOffset(5, tagsOffset);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.updatedAt?.millisecondsSinceEpoch);
        fbb.addInt64(8, object.lastAccessedAt?.millisecondsSinceEpoch);
        fbb.addInt64(9, object.accessCount);
        fbb.addOffset(10, noteTypeOffset);
        fbb.addOffset(11, handwritingImagePathOffset);
        fbb.addOffset(12, thumbnailPathOffset);
        fbb.addBool(13, object.isFavorite);
        fbb.addBool(14, object.isArchived);
        fbb.addOffset(15, digitizedInkDataOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final updatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final lastAccessedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final noteIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final subjectParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final noteTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 24, '');
        final tagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 14, []);
        final handwritingImagePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 26);
        final thumbnailPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 28);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final updatedAtParam = updatedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
        final lastAccessedAtParam = lastAccessedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(lastAccessedAtValue);
        final accessCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final isFavoriteParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          30,
          false,
        );
        final isArchivedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          32,
          false,
        );
        final digitizedInkDataParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 34);
        final object = Note(
          noteId: noteIdParam,
          title: titleParam,
          content: contentParam,
          subject: subjectParam,
          noteType: noteTypeParam,
          tags: tagsParam,
          handwritingImagePath: handwritingImagePathParam,
          thumbnailPath: thumbnailPathParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          lastAccessedAt: lastAccessedAtParam,
          accessCount: accessCountParam,
          isFavorite: isFavoriteParam,
          isArchived: isArchivedParam,
          digitizedInkData: digitizedInkDataParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    SearchHistory: obx_int.EntityDefinition<SearchHistory>(
      model: _entities[3],
      toOneRelations: (SearchHistory object) => [],
      toManyRelations: (SearchHistory object) => {},
      getId: (SearchHistory object) => object.id,
      setId: (SearchHistory object, int id) {
        object.id = id;
      },
      objectToFB: (SearchHistory object, fb.Builder fbb) {
        final queryOffset = fbb.writeString(object.query);
        final resultTypeOffset = fbb.writeString(object.resultType);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, queryOffset);
        fbb.addInt64(2, object.searchedAt.millisecondsSinceEpoch);
        fbb.addInt64(3, object.resultCount);
        fbb.addOffset(4, resultTypeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final queryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final resultTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final searchedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final resultCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final object = SearchHistory(
          query: queryParam,
          resultType: resultTypeParam,
          searchedAt: searchedAtParam,
          resultCount: resultCountParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    Subject: obx_int.EntityDefinition<Subject>(
      model: _entities[4],
      toOneRelations: (Subject object) => [],
      toManyRelations: (Subject object) => {},
      getId: (Subject object) => object.id,
      setId: (Subject object, int id) {
        object.id = id;
      },
      objectToFB: (Subject object, fb.Builder fbb) {
        final subjectIdOffset = fbb.writeString(object.subjectId);
        final nameOffset = fbb.writeString(object.name);
        final descriptionOffset = object.description == null
            ? null
            : fbb.writeString(object.description!);
        final iconPathOffset = object.iconPath == null
            ? null
            : fbb.writeString(object.iconPath!);
        final colorOffset = fbb.writeString(object.color);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, subjectIdOffset);
        fbb.addOffset(2, nameOffset);
        fbb.addOffset(3, descriptionOffset);
        fbb.addOffset(4, iconPathOffset);
        fbb.addOffset(5, colorOffset);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(7, object.updatedAt?.millisecondsSinceEpoch);
        fbb.addInt64(8, object.documentCount);
        fbb.addInt64(9, object.noteCount);
        fbb.addInt64(10, object.bookCount);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final updatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final subjectIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final colorParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final descriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final iconPathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final updatedAtParam = updatedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
        final documentCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final noteCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final bookCountParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final object = Subject(
          subjectId: subjectIdParam,
          name: nameParam,
          color: colorParam,
          description: descriptionParam,
          iconPath: iconPathParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          documentCount: documentCountParam,
          noteCount: noteCountParam,
          bookCount: bookCountParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Book] entity fields to define ObjectBox queries.
class Book_ {
  /// See [Book.id].
  static final id = obx.QueryIntegerProperty<Book>(_entities[0].properties[0]);

  /// See [Book.bookId].
  static final bookId = obx.QueryStringProperty<Book>(
    _entities[0].properties[1],
  );

  /// See [Book.title].
  static final title = obx.QueryStringProperty<Book>(
    _entities[0].properties[2],
  );

  /// See [Book.author].
  static final author = obx.QueryStringProperty<Book>(
    _entities[0].properties[3],
  );

  /// See [Book.isbn].
  static final isbn = obx.QueryStringProperty<Book>(_entities[0].properties[4]);

  /// See [Book.subject].
  static final subject = obx.QueryStringProperty<Book>(
    _entities[0].properties[5],
  );

  /// See [Book.description].
  static final description = obx.QueryStringProperty<Book>(
    _entities[0].properties[6],
  );

  /// See [Book.publisher].
  static final publisher = obx.QueryStringProperty<Book>(
    _entities[0].properties[7],
  );

  /// See [Book.publicationDate].
  static final publicationDate = obx.QueryStringProperty<Book>(
    _entities[0].properties[8],
  );

  /// See [Book.coverImagePath].
  static final coverImagePath = obx.QueryStringProperty<Book>(
    _entities[0].properties[9],
  );

  /// See [Book.barcodePath].
  static final barcodePath = obx.QueryStringProperty<Book>(
    _entities[0].properties[10],
  );

  /// See [Book.tags].
  static final tags = obx.QueryStringVectorProperty<Book>(
    _entities[0].properties[11],
  );

  /// See [Book.addedAt].
  static final addedAt = obx.QueryDateProperty<Book>(
    _entities[0].properties[12],
  );

  /// See [Book.lastAccessedAt].
  static final lastAccessedAt = obx.QueryDateProperty<Book>(
    _entities[0].properties[13],
  );

  /// See [Book.accessCount].
  static final accessCount = obx.QueryIntegerProperty<Book>(
    _entities[0].properties[14],
  );

  /// See [Book.totalPages].
  static final totalPages = obx.QueryIntegerProperty<Book>(
    _entities[0].properties[15],
  );

  /// See [Book.currentPage].
  static final currentPage = obx.QueryIntegerProperty<Book>(
    _entities[0].properties[16],
  );

  /// See [Book.readingStatus].
  static final readingStatus = obx.QueryStringProperty<Book>(
    _entities[0].properties[17],
  );

  /// See [Book.isFavorite].
  static final isFavorite = obx.QueryBooleanProperty<Book>(
    _entities[0].properties[18],
  );

  /// See [Book.isArchived].
  static final isArchived = obx.QueryBooleanProperty<Book>(
    _entities[0].properties[19],
  );
}

/// [Document] entity fields to define ObjectBox queries.
class Document_ {
  /// See [Document.id].
  static final id = obx.QueryIntegerProperty<Document>(
    _entities[1].properties[0],
  );

  /// See [Document.documentId].
  static final documentId = obx.QueryStringProperty<Document>(
    _entities[1].properties[1],
  );

  /// See [Document.title].
  static final title = obx.QueryStringProperty<Document>(
    _entities[1].properties[2],
  );

  /// See [Document.description].
  static final description = obx.QueryStringProperty<Document>(
    _entities[1].properties[3],
  );

  /// See [Document.subject].
  static final subject = obx.QueryStringProperty<Document>(
    _entities[1].properties[4],
  );

  /// See [Document.filePath].
  static final filePath = obx.QueryStringProperty<Document>(
    _entities[1].properties[5],
  );

  /// See [Document.fileName].
  static final fileName = obx.QueryStringProperty<Document>(
    _entities[1].properties[6],
  );

  /// See [Document.tags].
  static final tags = obx.QueryStringVectorProperty<Document>(
    _entities[1].properties[7],
  );

  /// See [Document.extractedText].
  static final extractedText = obx.QueryStringVectorProperty<Document>(
    _entities[1].properties[8],
  );

  /// See [Document.createdAt].
  static final createdAt = obx.QueryDateProperty<Document>(
    _entities[1].properties[9],
  );

  /// See [Document.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Document>(
    _entities[1].properties[10],
  );

  /// See [Document.lastAccessedAt].
  static final lastAccessedAt = obx.QueryDateProperty<Document>(
    _entities[1].properties[11],
  );

  /// See [Document.accessCount].
  static final accessCount = obx.QueryIntegerProperty<Document>(
    _entities[1].properties[12],
  );

  /// See [Document.documentType].
  static final documentType = obx.QueryStringProperty<Document>(
    _entities[1].properties[13],
  );

  /// See [Document.thumbnailPath].
  static final thumbnailPath = obx.QueryStringProperty<Document>(
    _entities[1].properties[14],
  );

  /// See [Document.fileSize].
  static final fileSize = obx.QueryIntegerProperty<Document>(
    _entities[1].properties[15],
  );

  /// See [Document.isFavorite].
  static final isFavorite = obx.QueryBooleanProperty<Document>(
    _entities[1].properties[16],
  );

  /// See [Document.isArchived].
  static final isArchived = obx.QueryBooleanProperty<Document>(
    _entities[1].properties[17],
  );
}

/// [Note] entity fields to define ObjectBox queries.
class Note_ {
  /// See [Note.id].
  static final id = obx.QueryIntegerProperty<Note>(_entities[2].properties[0]);

  /// See [Note.noteId].
  static final noteId = obx.QueryStringProperty<Note>(
    _entities[2].properties[1],
  );

  /// See [Note.title].
  static final title = obx.QueryStringProperty<Note>(
    _entities[2].properties[2],
  );

  /// See [Note.content].
  static final content = obx.QueryStringProperty<Note>(
    _entities[2].properties[3],
  );

  /// See [Note.subject].
  static final subject = obx.QueryStringProperty<Note>(
    _entities[2].properties[4],
  );

  /// See [Note.tags].
  static final tags = obx.QueryStringVectorProperty<Note>(
    _entities[2].properties[5],
  );

  /// See [Note.createdAt].
  static final createdAt = obx.QueryDateProperty<Note>(
    _entities[2].properties[6],
  );

  /// See [Note.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Note>(
    _entities[2].properties[7],
  );

  /// See [Note.lastAccessedAt].
  static final lastAccessedAt = obx.QueryDateProperty<Note>(
    _entities[2].properties[8],
  );

  /// See [Note.accessCount].
  static final accessCount = obx.QueryIntegerProperty<Note>(
    _entities[2].properties[9],
  );

  /// See [Note.noteType].
  static final noteType = obx.QueryStringProperty<Note>(
    _entities[2].properties[10],
  );

  /// See [Note.handwritingImagePath].
  static final handwritingImagePath = obx.QueryStringProperty<Note>(
    _entities[2].properties[11],
  );

  /// See [Note.thumbnailPath].
  static final thumbnailPath = obx.QueryStringProperty<Note>(
    _entities[2].properties[12],
  );

  /// See [Note.isFavorite].
  static final isFavorite = obx.QueryBooleanProperty<Note>(
    _entities[2].properties[13],
  );

  /// See [Note.isArchived].
  static final isArchived = obx.QueryBooleanProperty<Note>(
    _entities[2].properties[14],
  );

  /// See [Note.digitizedInkData].
  static final digitizedInkData = obx.QueryStringProperty<Note>(
    _entities[2].properties[15],
  );
}

/// [SearchHistory] entity fields to define ObjectBox queries.
class SearchHistory_ {
  /// See [SearchHistory.id].
  static final id = obx.QueryIntegerProperty<SearchHistory>(
    _entities[3].properties[0],
  );

  /// See [SearchHistory.query].
  static final query = obx.QueryStringProperty<SearchHistory>(
    _entities[3].properties[1],
  );

  /// See [SearchHistory.searchedAt].
  static final searchedAt = obx.QueryDateProperty<SearchHistory>(
    _entities[3].properties[2],
  );

  /// See [SearchHistory.resultCount].
  static final resultCount = obx.QueryIntegerProperty<SearchHistory>(
    _entities[3].properties[3],
  );

  /// See [SearchHistory.resultType].
  static final resultType = obx.QueryStringProperty<SearchHistory>(
    _entities[3].properties[4],
  );
}

/// [Subject] entity fields to define ObjectBox queries.
class Subject_ {
  /// See [Subject.id].
  static final id = obx.QueryIntegerProperty<Subject>(
    _entities[4].properties[0],
  );

  /// See [Subject.subjectId].
  static final subjectId = obx.QueryStringProperty<Subject>(
    _entities[4].properties[1],
  );

  /// See [Subject.name].
  static final name = obx.QueryStringProperty<Subject>(
    _entities[4].properties[2],
  );

  /// See [Subject.description].
  static final description = obx.QueryStringProperty<Subject>(
    _entities[4].properties[3],
  );

  /// See [Subject.iconPath].
  static final iconPath = obx.QueryStringProperty<Subject>(
    _entities[4].properties[4],
  );

  /// See [Subject.color].
  static final color = obx.QueryStringProperty<Subject>(
    _entities[4].properties[5],
  );

  /// See [Subject.createdAt].
  static final createdAt = obx.QueryDateProperty<Subject>(
    _entities[4].properties[6],
  );

  /// See [Subject.updatedAt].
  static final updatedAt = obx.QueryDateProperty<Subject>(
    _entities[4].properties[7],
  );

  /// See [Subject.documentCount].
  static final documentCount = obx.QueryIntegerProperty<Subject>(
    _entities[4].properties[8],
  );

  /// See [Subject.noteCount].
  static final noteCount = obx.QueryIntegerProperty<Subject>(
    _entities[4].properties[9],
  );

  /// See [Subject.bookCount].
  static final bookCount = obx.QueryIntegerProperty<Subject>(
    _entities[4].properties[10],
  );
}
